### ISSUE TITLE
Problem with App

### ISSUE THREAD

**Issue by carlloshenrry** [Kommandat/mlkit-demo#1]
Hello, how is everything ? Your algorithm doesn't seem to be working, when the image is chosen, it is not treated in the application. I was trying to implement an OCR algorithm for my app using expo and I couldn't manage it anyway. Searching through several forums I just found your project, do you mind giving me some tips? I couldn't eject the Expo to migrate to use other tools like react-native-camera which itself has OCR included. If you can help me, I'm so grateful.

**Comment by Kommandat** [comment]
Sorry! I created this repo to play around with Expo + MLKit but never fixed it after I figured out how to integrate the two.

So the key is to use Expo's new EAS service. You'll need to pay $30 / month though (first-month free). I'm happy to share that my app (not this one) is working with MLKit and OCR.

Here's an issue that might be helpful --> https://github.com/agoldis/react-native-mlkit-ocr/issues/12

Let me know if you have any questions. When I get around to it, I'll update this app to use EAS as well.

**Comment by carlloshenrry** [comment]
Thanks for answering, yes I still have some questions... would there be any free option to implement OCR at the expo? I thought about using the react-native-camera tool to use the OCR included in it, but as I started my project with expo I'm struggling to eject, with the new updates from the Expo SDK I'm a little lost and missing of good tutoring slow me down. Do you think react-native-camera is a good solution, if so how could I implement it? I'm not able to generate the android and ios files to work pure react tools. I've already looked at the tutorials on EAS and running Expo run: android and ios. What would be the order to make my application work? First do I eject or build the EAS?

**Comment by Kommandat** [comment]
I personally think the $30 / month is worth it for the ability to remain an Expo managed app and use react-native-mlkit-ocr. Maybe react-native-camera would work too with EAS (I don't have experience with that). Also, you're supporting the Expo team, which is a plus.

If you're not planning on using EAS then yes, you'd need to eject from expo and use either react-native-mlkit-ocr or react-native-camera. And that would be free.

**Comment by carlloshenrry** [comment]
Got it, thank you very much for the reply. Well, I'm from Brazil and the subscription fee is 5x more expensive for me. Do you know any tutorial to eject with sdk42 other than the expo website? I get lost with their page. Since already thank you very much for your help.

**Comment by Kommandat** [comment]
Got it and makes sense. I do think Expo is planning on making EAS free at some point. There is a 1 month free trial if you think you can build your app in 1 month. Lastly, maybe if you reach out to Expo they'll be willing to extend your free trial. They're nice people and might help you out.

I've never ejected from Expo before so I'm afraid I can't help much there 😞

**Comment by carlloshenrry** [comment]
No problem, I thank you for your attention and help. I am honored to have the opportunity to gain knowledge from people from other regions. Thank you for your attention, I wish you success in your career and all the best in your life. Thanks.

**Comment by Kommandat** [comment]
Thanks Carlos! Wishing you the best too. Let me know if there's anything else I can help with for your project in the future!
